name       : plano-theme
version    : 3.36.2
release    : 8
source     :
    - https://github.com/lassekongo83/plano-theme/archive/v3.36-2.tar.gz : 16653048f733c1067020bc337f54b2dccb31b7aab823aac3b473d0f29ac2ffe5
homepage   : https://github.com/lassekongo83/plano-theme
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Plano GTK & GNOME Shell Theme
description: |
    A flat Plano GTK & GNOME Shell Theme
builddeps  :
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
