name       : plano-theme
version    : 3.30.2
release    : 4
source     :
    - https://github.com/lassekongo83/plano-theme/archive/v3.30-2.tar.gz : 3a70edb7d4310d5c5e1529b009ab5162de6e10e2bff81cb0b0db3889c8fd5238
license    : GPL-3.0-only
component  : desktop.theme
summary    : Plano GTK & GNOME Shell Theme
description: |
    A flat Plano GTK & GNOME Shell Theme
rundeps    :
    - gtk2-engine-murrine
    - gtk-engines
install    : |
    install -dm00644 $installdir/usr/share/themes/plano-theme/
    cp -r gnome-shell $installdir/usr/share/themes/plano-theme/
    cp -r gtk-3.0 $installdir/usr/share/themes/plano-theme/
    cp -r gtk-2.0 $installdir/usr/share/themes/plano-theme/
