name       : plano-theme
version    : 3.38.1
release    : 9
source     :
    - https://github.com/lassekongo83/plano-theme/archive/v3.38-1.tar.gz : 0f315c8beb53723ea0f669f004ade986ef8ac20c6d25d988b7aa2c6caa98eba4
homepage   : https://github.com/lassekongo83/plano-theme
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Plano GTK & GNOME Shell Theme
description: |
    A flat Plano GTK & GNOME Shell Theme
builddeps  :
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
