name       : plano-theme
version    : 3.34.2
release    : 7
source     :
    - https://github.com/lassekongo83/plano-theme/archive/v3.34-2.tar.gz : d94556d38b52f0444f712ddd8356e9b7a5338c95c79bd6203e328e15be1214ed
homepage   : https://github.com/lassekongo83/plano-theme
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Plano GTK & GNOME Shell Theme
description: |
    A flat Plano GTK & GNOME Shell Theme
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes/plano-theme/
    cp -r {gnome-shell,gtk-2.0,gtk-3.0} $installdir/usr/share/themes/plano-theme/
    rm -f {COPYING,README.md}$installdir/usr/share/themes/plano-theme/gnome-shell/gnome-shell-sass/
