name       : plano-theme
version    : 3.34.1
release    : 6
source     :
    - https://github.com/lassekongo83/plano-theme/archive/v3.34-1.tar.gz : 9caa1fe123462e4d6f9cfef6c102ea4db908a5fcb786312b5e5f899846ee2fc3
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Plano GTK & GNOME Shell Theme
description: |
    A flat Plano GTK & GNOME Shell Theme
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
install    : |
    install -dm00644 $installdir/usr/share/themes/plano-theme/
    cp -r gnome-shell $installdir/usr/share/themes/plano-theme/
    cp -r gtk-3.0 $installdir/usr/share/themes/plano-theme/
    cp -r gtk-2.0 $installdir/usr/share/themes/plano-theme/
