name       : plano-theme
version    : '4.0'
release    : 10
source     :
    - https://github.com/lassekongo83/plano-theme/archive/v4.0.tar.gz : c33ac656c0895b81fc9491d2921fa0d6a8c8224169bd35efc7d45137663d0a12
homepage   : https://github.com/lassekongo83/plano-theme
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Plano GTK & GNOME Shell Theme
description: |
    A flat Plano GTK & GNOME Shell Theme
builddeps  :
    - sassc
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
