name       : plano-theme
version    : 3.28.3
release    : 2
source     :
    - https://github.com/lassekongo83/plano-theme/archive/v3.28-3.tar.gz : 4f8372cb85fd0c389e72f25b7f84bb3b8a0c15098a5670b46da3b2644dd2bb08
license    : GPL-3.0
component  : desktop.theme
summary    : Plano GTK & GNOME Shell Theme
description: |
    A flat Plano GTK & GNOME Shell Theme
rundeps    :
    - gtk2-engine-murrine
    - gtk-engines
install    : |
    mkdir -p %installroot%/usr/share/themes/plano-theme/
    cp -r gnome-shell %installroot%/usr/share/themes/plano-theme/
    cp -r gtk-3.0 %installroot%/usr/share/themes/plano-theme/
    cp -r gtk-2.0 %installroot%/usr/share/themes/plano-theme/
