name       : plano-theme
version    : 3.22
release    : 1
source     :
    - https://github.com/lassekongo83/plano-theme/archive/3.22-1.tar.gz : 4f61c267a14a72b082468fa9e7342a22a31c9a51677c85f5cefb9405d61ce476
license    : GPL-3.0
component  : desktop.theme
summary    : Plano GTK & GNOME Shell Theme
description: |
    A flat Plano GTK & GNOME Shell Theme
rundeps    :
    - gtk2-engine-murrine
    - gtk-engines
install    : |
    mkdir -p %installroot%/usr/share/themes/plano-theme/
    cp -r gnome-shell %installroot%/usr/share/themes/plano-theme/
    cp -r gtk-3.0 %installroot%/usr/share/themes/plano-theme/
    cp -r gtk-2.0 %installroot%/usr/share/themes/plano-theme/
